---

name: Release

on:
  workflow_call:
    inputs:
      allowed_owner:
        description: 'Only allow this owner'
        required: true
        type: string
    secrets:
      username:
        description: 'The forge username to use'
        required: true
      api_key:
        description: 'The forge API key'
        required: true

env:
  BUNDLE_WITHOUT: development:test:system_tests

jobs:
  deploy:
    name: 'deploy to forge'
    runs-on: ubuntu-latest
    if: github.repository_owner == allowed_owner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Build and Deploy
        env:
          # Configure secrets here:
          #  https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets
          BLACKSMITH_FORGE_USERNAME: '${{ secrets.username }}'
          BLACKSMITH_FORGE_API_KEY: '${{ secrets.api_key }}'
        run: bundle exec rake module:push
